[package]
name = "corelang"
version = "0.1.0"
authors = ["Solène Husseini <tanguy1.husseini@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
